services: 
  frontend: 
    build: 
      context: ./tree-app-frontend/
      dockerfile: DOCKERFILE
    ports: 
      - "3000:3000"
    depends_on: 
      - backend

  backend: 
    build: 
      context: ./tree-app-backend
      dockerfile: DOCKERFILE
    ports:
      - "5000:5000"
